config/routes.rb
Stackflow::Application.routes.draw do
  get "home/index"
  get "posts/refresh"
  devise_for :members
   resources :posts do
  	resources :answers
end
root to: "posts#index"
post "posts/new"

  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :post
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :post
 
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :answers
	has_many :activities
	validates :question, presence: true,
                    length: { minimum: 1 }


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
		 if member_signed_in?
		  	@post = Post.find(params[:post_id])
		 
		  puts params[:answer]

			@ans = @post.answers.new
			@ans.ans = params[:answer][:ans]
			@ans.commenter=current_member.email
			if @ans.save
@act = Activity.new
      
   @act.doer=current_member.email
  @act.activity="answered"
  @act.post_id=@post.id
  @act.save 

		# @post = Post.find(params[:post_id])
   # @ans = @post.answers.create(params[:answer].permit(:commenter, :ans))
    			redirect_to post_path(@post)
  			else
    			redirect_to new_member_session_path
  			end
   
  		end
	end
	private

  def answer_params
    params.require(:answer).permit(:ans)
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def refresh
		
		@activities = Activity.find(:all, :order => "id desc", :limit => 8)
		 respond_to do |format|
    format.js
  end
end

	def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:question))
    	@act = Activity.new
  @act.doer=current_member.email
  @act.activity="edited"
  @act.acted_on=@post.id
  @act.save 
      redirect_to @post
    else
      render 'edit'
    end
  end
	
  def edit
    @post = Post.find(params[:id])
  end

	def index
    @posts = Post.all
@activities = Activity.find(:all, :order => "id desc", :limit => 8)
		#@activities = Activities.all
		
   end

	def show 
	 if member_signed_in?

 
      @post = Post.find(params[:id])
      @post.views=@post.views+1
      @post.save

      if(@post.commenter != current_member.email)
      @act = Activity.new 
   @act.doer=current_member.email
  @act.activity="viewed"
  @act.post_id=@post.id
  @act.save 
end
@activities = Activity.find(:all, :order => "id desc", :limit => 8)
 else
    redirect_to new_member_session_path
  end
   end

	def new
    if member_signed_in?
@activities = Activity.find(:all, :order => "id desc", :limit => 8)
	@posts = Post.new	
  else
    redirect_to new_member_session_path
  end
	end

	def create
  
  @post = Post.new(post_params)
  @post.commenter=current_member.email

 if @post.save
 	@act = Activity.new
  @act.doer=current_member.email
  @act.activity="posted a question"
  @act.post_id =@post.id
  @act.save 
    redirect_to @post
  else
    render 'new'
end
 end
private
  def post_params
    params.require(:post).permit(:question)
end
end

  

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<% if member_signed_in? %>

<h3>you have succesfully signed in</h3>
<%= link_to "Sign Out", destroy_member_session_path, :method => :delete %>

<% else %>

<h1> welcom to rails community</h1>
<%= link_to "Sign In", new_member_session_path, :method => :get %>
<%= link_to "Sign up", new_member_registration_path, :method => :get %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stackflow</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <style>
  .na {
    line-height:30px;
    background-color:#eeeeee;
    width:300px;
    float:right;
    padding:5px;        
}
.sectio {
    width:500px;
    float:left;
    padding:10px;    
}
  </style>
  <script>
$(document).ready(function() {
    setInterval(function () {
          $.ajax('/posts/refresh');
    } , 1000);          
}); 
</script>
</head>
 <body onload="myFunction()">
    <header  class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
       
        <nav>
          <ul class="nav navbar-nav navbar-right">
           <li style="color:white; text-align:center"><% if member_signed_in? %>
  <h4><%= current_member.email %></h4>
<% end %></li>
            <li><%= link_to "Home",   posts_path %></li>
            <li><% if member_signed_in? %>
<%= link_to "Sign Out", destroy_member_session_path, :method => :delete %>
<% else %>
              <%= link_to "Sign In", new_member_session_path, :method => :get %>
            <% end %>
          </li>
          </ul>
        </nav>
      </div>
    </header>
    
    <div  style="margin-top:100px;margin-bottom:100px" class="container">
      <%= yield %>
    </div>
    <footer style="background-color:grey" class="navbar navbar-fixed-bottom navbar-inverse">
      <div   class="container">
       
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li>copyright@stackflow</li>
           
          </ul>
        </nav>
      </div>
    </footer>
  </body>
</html>

app/views/posts/_activities.html.erb
   
       <table style="width:280px; margin-top:30px">
 <tr><th style= "text-align:center; size:6; color:red"> Recent activities</th></tr>
         
         <% @activities.each do |activity| %>

         <tr><td><strong><%= activity.created_at.strftime('%D at %H:%M:%S') %></strong> </td></tr>
         <tr><td> <% msg=activity.doer + " " + activity.activity + "  " + "'" +activity.post.question + "'" %>
           <%= link_to   msg ,post_path(activity.post) %> </td></tr>    
          <% end %>
          </table>
         

app/views/posts/edit.html.erb
<h1>Editing post</h1>
 
<%= form_for :post, url: post_path(@post.id), method: :patch do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :Question %><br>
    <%= f.text_field :question %>
  </p>
 
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div  id="updates" class="na" >
       <%= render partial: "activities" %>
        </div>
<div class="sectio" >
<div class="btn-group ">
  <%= button_to "ASK QUESTION", new_post_path, :class => "btn" %>
</div>
<!DOCTYPE html>

       <table style="width:500px; margin-top:30px"class="table table-striped table-bordered table-condensed">
       <th colspan="3"> QUESTIONS LIST</th>
<% @posts.each do |post| %>

<tr>
<td style="width:30px"><%=   post.answers.count %> ans</td>
<td style="width:50px"><%=   post.views %> views</td>
<td style="width:20px"><%= link_to  post.question, post_path(post) %></td>
</tr>

     
        <% end %>
</table>
</div>
    
        
   

app/views/posts/new.html.erb
  

  <div class="sectio">
<%= form_for :post, url: posts_path do |f| %>  <p>

    <%= f.label :Question %> 
    <%= f.text_field :question %>
  </p>
 
 
  <p>
    <%= f.submit %>
  </p>

<%= link_to 'see questions list', posts_path %>


</div>

<% end %>

        <div  id="updates" class="na" >
        
       <%= render partial: "activities" %>
      
        </div>
  

app/views/posts/refresh.js.erb
 $("#updates").html("<%= escape_javascript(render partial: 'activities', locals: { activities: @activities } ) %>"); 

app/views/posts/show.html.erb
<div class="sectio">
<p>
  <strong>commenter:</strong>
  <%= @post.commenter %>
</p>

<p>
  <strong>Question:</strong>
  <%= @post.question %>
</p>
 
<% if (current_member.email== @post.commenter) %>
 <%= link_to 'Edit', edit_post_path(@post) %>
 <% end %>
 <h2>Add a comment:</h2>
<%= form_for :answer, url: post_answers_path(@post) do |f| %> 
  <p>
    <%= f.label :Answer %><br />
    <%= f.text_field :ans %>
  </p>
 <p>
   
    </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 <h2>Answer</h2>
<% @post.answers.each do |answer| %>

  <p>
    <strong>Commenter:</strong>
    <%= answer.commenter %>
  </p>
 
  <p>
    <strong>Answer:</strong>
    <%= answer.ans %>
  </p>
 
 
<% end %>
</div>
        <div  id="updates" class="na" >
       <%= render partial: "activities" %>
        </div>
   